Vision
ori-coval/eilon-training-swerve pull request #4
Opened 2024-06-01 08:14 UTC by eilonhuppert

2024-06-20 16:02 UTC, ori-coval requested changes
מה עם להשתמש במידע שקיבלת מהעיבוד תמונה בסווארב כדי לעדכן את המיקום

2024-06-27 09:27 UTC, eilonhuppert commented
![image](https://github.com/ori-coval/eilon-training-swerve/assets/111500283/abc2a914-90df-4a33-8f6c-e95c557496f8)
יעני זה?

2024-06-27 09:28 UTC, eilonhuppert commented
למה אנחנו לא משתמשים גם במצלמה השניה?

2024-06-27 10:46 UTC, ori-coval commented
> למה אנחנו לא משתמשים גם במצלמה השניה?

כי יש שתי מצלמות על הרובוט

2024-06-27 10:46 UTC, ori-coval commented
> ![image](https://private-user-images.githubusercontent.com/111500283/343713978-abc2a914-90df-4a33-8f6c-e95c557496f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODU0NzcsIm5iZiI6MTcxOTQ4NTE3NywicGF0aCI6Ii8xMTE1MDAyODMvMzQzNzEzOTc4LWFiYzJhOTE0LTkwZGYtNGEzMy04ZjZjLWU5NWM1NTc0OTZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMDQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWZjZWE2MzU4MmJjODMwMTMxZjY3YjA4N2M4ODFjNTdkYWQ1ZGViYjk3MzYwZTFhYWY3YzhjOTBjZThlOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RysHlzAywPlrOVK2XWSVtm6oFvIojhgDXKOeFJp2Bwc) יעני זה?

כן

2024-06-27 11:07 UTC, eilonhuppert commented
> > למה אנחנו לא משתמשים גם במצלמה השניה?
> 
> כי יש שתי מצלמות על הרובוט

אז למה לא להשתמש בשניהם

2024-06-27 11:08 UTC, eilonhuppert commented
ואם 

> > ![image](https://private-user-images.githubusercontent.com/111500283/343713978-abc2a914-90df-4a33-8f6c-e95c557496f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODU0NzcsIm5iZiI6MTcxOTQ4NTE3NywicGF0aCI6Ii8xMTE1MDAyODMvMzQzNzEzOTc4LWFiYzJhOTE0LTkwZGYtNGEzMy04ZjZjLWU5NWM1NTc0OTZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMDQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWZjZWE2MzU4MmJjODMwMTMxZjY3YjA4N2M4ODFjNTdkYWQ1ZGViYjk3MzYwZTFhYWY3YzhjOTBjZThlOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RysHlzAywPlrOVK2XWSVtm6oFvIojhgDXKOeFJp2Bwc) יעני זה?
> 
> כן

אז תאשר לי את הבעיה שאגב אם היא הייתה קיימת היא הייתה קיימת בסוורב ולא כאן

2024-06-27 17:46 UTC, ori-coval commented
> > > למה אנחנו לא משתמשים גם במצלמה השניה?
> > 
> > 
> > כי יש שתי מצלמות על הרובוט
> 
> אז למה לא להשתמש בשניהם

אנחנו כן

2024-06-27 17:47 UTC, ori-coval commented
> ואם
> 
> > > ![image](https://private-user-images.githubusercontent.com/111500283/343713978-abc2a914-90df-4a33-8f6c-e95c557496f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODU0NzcsIm5iZiI6MTcxOTQ4NTE3NywicGF0aCI6Ii8xMTE1MDAyODMvMzQzNzEzOTc4LWFiYzJhOTE0LTkwZGYtNGEzMy04ZjZjLWU5NWM1NTc0OTZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMDQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWZjZWE2MzU4MmJjODMwMTMxZjY3YjA4N2M4ODFjNTdkYWQ1ZGViYjk3MzYwZTFhYWY3YzhjOTBjZThlOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RysHlzAywPlrOVK2XWSVtm6oFvIojhgDXKOeFJp2Bwc) יעני זה?
> > 
> > 
> > כן
> 
> אז תאשר לי את הבעיה שאגב אם היא הייתה קיימת היא הייתה קיימת בסוורב ולא כאן

הבעיה היא כאן ולא בסווארב בגלל שבסווארב עדיין אין לך את מחלקת VISION

2024-06-30 19:30 UTC, ori-coval commented
this not how you use github

2024-06-30 19:30 UTC, closed without merging